sudo: required

services:
  - docker

before_install:
  - docker build -t german-mesa/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run german-mesa/react-test npm test -- --coverage

after_success:
  # Build productive images
  - docker build -t german-mesa/multi-client ./client
  - docker build -t german-mesa/multi-nginx ./nginx
  - docker build -t german-mesa/multi-postgres ./postgres
  - docker build -t german-mesa/multi-server ./server
  - docker build -t german-mesa/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push to github
  - docker push german-mesa/multi-client
  - docker push german-mesa/multi-nginx
  - docker push german-mesa/multi-postgres    
  - docker push german-mesa/multi-server
  - docker push german-mesa/multi-worker  